# use the Python 3.5 language
language: python
python:
  - "3.5"

# cache to improve build speed
cache:
  directories:
    - $HOME/.pip-cache/

# install mdl for checking Markdown
before_install:
  - gem install mdl

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt --cache-dir $HOME/.pip-cache

# install the nltk wordnet package and set environment variable
before_script:
  - python -m nltk.downloader wordnet
  - export SEED_HOME="/home/travis/build/gkapfham/seed"

# command to run tests
script: pytest tests --runslow
