# use the Python 3.5 language
language: python
python:
  - "3.5"
cache: pip
# command to install dependencies
install: "pip install -r requirements.txt"
# install the nltk packages and set environment variable
before_script:
  - python -m nltk.downloader wordnet
  - export SEED_HOME="/home/travis/build/gkapfham/seed"
# command to run tests
script: pytest tests --runslow
